Update required Puppet version to 3.7
Due to bug PUP-1597 (https://tickets.puppetlabs.com/browse/PUP-1597), this module will raise an
error during catalog compilation ("Error: undefined method `ref' for nil:NilClass") when run with a
version of Puppet prior to 3.7 if "mysql" is used as the database.

Here is the commit that triggers the bug:
https://github.com/puppet-community/puppet-jira/commit/412efe3e7accb892bceadcf59b2d32f063faeb06#diff-a276806bea2dfcf1f57c33aee19c7309R114